{% set name = "pypeit" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e781e111b4d410968a9e7b75fbfbf3a3390afe0f1c77b8c26bbc33c314bd257a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]
  entry_points:
    - pypeit_chk_2dslits = pypeit.scripts.chk_2dslits:entry_point
    - pypeit_chk_for_calibs = pypeit.scripts.chk_for_calibs:entry_point
    - pypeit_coadd_1dspec = pypeit.scripts.coadd_1dspec:entry_point
    - pypeit_coadd_2dspec = pypeit.scripts.coadd_2dspec:entry_point
    - pypeit_coadd_datacube = pypeit.scripts.coadd_datacube:entry_point
    - pypeit_flux_calib = pypeit.scripts.flux_calib:entry_point
    - pypeit_flux_setup = pypeit.scripts.flux_setup:entry_point
    - pypeit_lowrdx_pixflat = pypeit.scripts.lowrdx_pixflat:entry_point
    - pypeit_qa_html = pypeit.scripts.qa_html:entry_point
    - pypeit_ql_keck_nires = pypeit.scripts.ql_keck_nires:entry_point
    - pypeit_ql_mos = pypeit.scripts.ql_mos:entry_point
    - pypeit_sensfunc = pypeit.scripts.sensfunc:entry_point
    - pypeit_setup = pypeit.scripts.setup:entry_point
    - pypeit_show_arxiv = pypeit.scripts.show_arxiv:entry_point
    - pypeit_tellfit = pypeit.scripts.tellfit:entry_point
    - pypeit_trace_edges = pypeit.scripts.trace_edges:entry_point
    - run_pypeit = pypeit.scripts.run_pypeit:entry_point
    - pypeit_arcid_plot = pypeit.scripts.arcid_plot:entry_point
    - pypeit_chk_alignments = pypeit.scripts.chk_alignments:entry_point
    - pypeit_chk_edges = pypeit.scripts.chk_edges:entry_point
    - pypeit_chk_flats = pypeit.scripts.chk_flats:entry_point
    - pypeit_chk_tilts = pypeit.scripts.chk_tilts:entry_point
    - pypeit_chk_wavecalib = pypeit.scripts.chk_wavecalib:entry_point
    - pypeit_compare_sky = pypeit.scripts.compare_sky:entry_point
    - pypeit_identify = pypeit.scripts.identify:entry_point
    - pypeit_lowrdx_skyspec = pypeit.scripts.lowrdx_skyspec:entry_point
    - pypeit_obslog = pypeit.scripts.obslog:entry_point
    - pypeit_ql_keck_mosfire = pypeit.scripts.ql_keck_mosfire:entry_point
    - pypeit_show_1dspec = pypeit.scripts.show_1dspec:entry_point
    - pypeit_show_2dspec = pypeit.scripts.show_2dspec:entry_point
    - pypeit_show_wvcalib = pypeit.scripts.show_wvcalib:entry_point
    - pypeit_skysub_regions = pypeit.scripts.skysub_regions:entry_point
    - pypeit_view_fits = pypeit.scripts.view_fits:entry_point

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - extension-helpers >=0.1
    - setuptools_scm >=5
  run:
    - python
    - numpy >=1.18
    - astropy >=4.0
    - scipy >=1.4
    - matplotlib-base >=3.1
    - qtpy >=1.9
    - pyyaml >=5.1
    - configobj >=5.0.6
    - scikit-learn >=0.20
    - ipython >=7.2.0
    - ginga >=3.0
    - packaging >=19.0
    - linetools >=0.3.dev2231
    - extension-helpers >=0.1
    - shapely >=1.7.1
    - requests >=2.23
    - bottleneck >=1.3

test:
  requires:
    - pytest
  imports:
    - pypeit
  commands:
    - run_pypeit -h
    - pytest --pyargs {{ name }}

about:
  home: https://github.com/pypeit/PypeIt
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.rst
    - licenses/PYDL_LICENSE.rst
  summary: The Python Spectroscopic Data Reduction Pipeline.

  description: |
    PypeIt is a Python package for semi-automated reduction of astronomical,
    spectroscopic data. Its algorithms build on decades-long development of
    previous data reduction pipelines by the developers. PypeIt is a set of
    commands designed to perform the reduction without any additional coding.
  doc_url: https://pypeit.readthedocs.io/
  dev_url: https://github.com/pypeit/PypeIt

extra:
  recipe-maintainers:
    - finagle29
