{% set name = "pypeit" %}
{% set version = "1.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 328648c3ce0d4d15c8eaca78e013161192f74103ad4a9963d206dd81e956b687


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39 or py>310]
  entry_points:
    - pypeit_cache_github_data = pypeit.scripts.cache_github_data:CacheGithubData.entry_point
    - pypeit_chk_for_calibs = pypeit.scripts.chk_for_calibs:ChkForCalibs.entry_point
    - pypeit_chk_noise_1dspec = pypeit.scripts.chk_noise_1dspec:ChkNoise1D.entry_point
    - pypeit_chk_noise_2dspec = pypeit.scripts.chk_noise_2dspec:ChkNoise2D.entry_point
    - pypeit_coadd_1dspec = pypeit.scripts.coadd_1dspec:CoAdd1DSpec.entry_point
    - pypeit_coadd_2dspec = pypeit.scripts.coadd_2dspec:CoAdd2DSpec.entry_point
    - pypeit_coadd_datacube = pypeit.scripts.coadd_datacube:CoAddDataCube.entry_point
    - pypeit_collate_1d = pypeit.scripts.collate_1d:Collate1D.entry_point
    - pypeit_flux_calib = pypeit.scripts.flux_calib:FluxCalib.entry_point
    - pypeit_flux_setup = pypeit.scripts.flux_setup:FluxSetup.entry_point
    - pypeit_install_extinctfile = pypeit.scripts.install_extinctfile:InstallExtinctfile.entry_point
    - pypeit_install_linelist = pypeit.scripts.install_linelist:InstallLinelist.entry_point
    - pypeit_install_ql_masters = pypeit.scripts.install_ql_masters:InstallQLMasters.entry_point
    - pypeit_install_telluric = pypeit.scripts.install_telluric:InstallTelluric.entry_point
    - pypeit_lowrdx_skyspec = pypeit.scripts.lowrdx_skyspec:LowRDXSkySpec.entry_point
    - pypeit_multislit_flexure = pypeit.scripts.multislit_flexure:MultiSlitFlexure.entry_point
    - pypeit_obslog = pypeit.scripts.obslog:ObsLog.entry_point
    - pypeit_parse_calib_id = pypeit.scripts.parse_calib_id:ParseCalibID.entry_point
    - pypeit_parse_slits = pypeit.scripts.parse_slits:ParseSlits.entry_point
    - pypeit_qa_html = pypeit.scripts.qa_html:QAHtml.entry_point
    - pypeit_ql = pypeit.scripts.ql:QL.entry_point
    - pypeit_ql_jfh_multislit = pypeit.scripts.ql_multislit:QL_Multislit.entry_point
    - run_pypeit = pypeit.scripts.run_pypeit:RunPypeIt.entry_point
    - pypeit_sensfunc = pypeit.scripts.sensfunc:SensFunc.entry_point
    - pypeit_setup = pypeit.scripts.setup:Setup.entry_point
    - pypeit_show_arxiv = pypeit.scripts.show_arxiv:ShowArxiv.entry_point
    - pypeit_show_wvcalib = pypeit.scripts.show_wvcalib:ShowWvCalib.entry_point
    - pypeit_tellfit = pypeit.scripts.tellfit:TellFit.entry_point
    - pypeit_trace_edges = pypeit.scripts.trace_edges:TraceEdges.entry_point
    - pypeit_chk_alignments = pypeit.scripts.chk_alignments:ChkAlignments.entry_point
    - pypeit_chk_edges = pypeit.scripts.chk_edges:ChkEdges.entry_point
    - pypeit_chk_flats = pypeit.scripts.chk_flats:ChkFlats.entry_point
    - pypeit_chk_wavecalib = pypeit.scripts.chk_wavecalib:ChkWaveCalib.entry_point
    - pypeit_compare_sky = pypeit.scripts.compare_sky:CompareSky.entry_point
    - pypeit_identify = pypeit.scripts.identify:Identify.entry_point
    - pypeit_ql_multislit = pypeit.scripts.ql_multislit:QL_MOS.entry_point
    - pypeit_show_1dspec = pypeit.scripts.show_1dspec:Show1DSpec.entry_point
    - pypeit_show_2dspec = pypeit.scripts.show_2dspec:Show2DSpec.entry_point
    - pypeit_skysub_regions = pypeit.scripts.skysub_regions:SkySubRegions.entry_point
    - pypeit_view_fits = pypeit.scripts.view_fits:ViewFits.entry_point

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - extension-helpers >=0.1
    - setuptools_scm >=5
  run:
    - python
    - numpy >=1.20,<1.24
    - astropy >=4.3
    - scipy >=1.6
    - matplotlib-base >=3.3
    - qtpy >=1.9
    - pyyaml >=5.1
    - configobj >=5.0.6
    - scikit-learn >=1.0
    - ipython >=7.10.0
    - ginga >=3.0
    - packaging >=0.19
    - linetools >=0.3.dev2231
    - extension-helpers >=0.1
    - shapely >=1.7
    - requests >=2.23
    - bottleneck >=1.2
    - scikit-image
    - pygithub

test:
  requires:
    - pytest >= 6
  imports:
    - pypeit
  commands:
    - run_pypeit -h
    - pytest --pyargs {{ name }}

about:
  home: https://github.com/pypeit/PypeIt
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.rst
    - licenses/PYDL_LICENSE.rst
  summary: The Python Spectroscopic Data Reduction Pipeline.

  description: |
    PypeIt is a Python package for semi-automated reduction of astronomical,
    spectroscopic data. Its algorithms build on decades-long development of
    previous data reduction pipelines by the developers. PypeIt is a set of
    commands designed to perform the reduction without any additional coding.
  doc_url: https://pypeit.readthedocs.io/
  dev_url: https://github.com/pypeit/PypeIt

extra:
  recipe-maintainers:
    - kbwestfall
    - finagle29
